### ISSUE TITLE
Linking errors under Ubuntu 20

### ISSUE THREAD

**Issue by dbrnz** [bjia56/portable-python-cmake-buildsystem#10]
My first attempt building under Ubuntu 20 resulted in:
```
/usr/bin/ld: lib/libpython3.12.so: undefined reference to `be64toh'
/usr/bin/ld: lib/libpython3.12.so: undefined reference to `le64toh'
/usr/bin/ld: lib/libpython3.12.so: undefined reference to `htobe32'
/usr/bin/ld: lib/libpython3.12.so: undefined reference to `htobe64'
/usr/bin/ld: lib/libpython3.12.so: undefined reference to `be32toh'
/usr/bin/ld: lib/libpython3.12.so: undefined reference to `le32toh'
/usr/bin/ld: lib/libpython3.12.so: undefined reference to `htole64'
/usr/bin/ld: lib/libpython3.12.so: undefined reference to `htole32'
```

The fix is to set `-D_DEFAULT_SOURCE` in `CMAKE_C_FLAGS`. The compile then succeeds with the build subsequently failing because of issue #9.

**Comment by bjia56** [comment]
Do you see this on MacOS, or just Ubuntu/Linux?

**Comment by bjia56** [comment]
Also, which compiler did you use? gcc/clang/other?

**Comment by dbrnz** [comment]
Under Ubuntu 20 with gcc -- macOS with clang was fine.

See [here](https://stackoverflow.com/questions/19525378/be64toh-not-linking-or-being-declared-when-compiling-with-std-c99#19525401) for details of the fix.

**Comment by bjia56** [comment]
Hi @dbrnz, if you get a chance can you please test if https://github.com/bjia56/portable-python-cmake-buildsystem/pull/13 resolves the issue? The CMake definitions in this repo now add that macro when GCC is detected.

**Comment by dbrnz** [comment]
All is good under Ubuntu 20 with your `default-source-macro` branch, thanks!
